install: ""
php_version: ""
filesystem_version: ""
prod_install: drivers072120
stage_install: ""
dev_install: ""
push_environment: ""
pull_environment: ""
last_ssh_event: "2020-08-24T21:06:25-07:00"
last_push_event: "2020-08-24T21:05:30-07:00"
mysql_volume_mount_type: ""
mysql_root_password: ""
mysql_user_password: ""
mysql_user_name: ""
mysql_database_name: ""
xdebug_off_by_default: false
force_ssl: false
wp_debug: false
wp_debug_cli: false
